module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LkUGJWQySXYBLqY7FAf3ed',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://h.uguu.se/UdREjnTf.jpg',
    RCD_IMAGE_PATH: 'https://h.uguu.se/UdREjnTf.jpg',
    NEWSLETTER_JID: '120363425215440435@newsletter',
    NEWSLETTER_MESSAGE_ID: '120363425215440435@newsletter',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐘𝐎𝐔 𝐌𝐃 𝐁𝐎𝐓',
    OWNER_NAME: '𝐘ꭷ︩︪֟፝͡υ  ƚᩬᩧ𝛆̽ɕ͛¢н᥊🌙',
    OWNER_NUMBER: '50941319791,50955034382',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> *ᴍᴀᴅᴇ ɪɴ ʙʏ ʏᴏᴜ ᴛᴇᴄʜx🌙*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbCzeHxDeON8UEum3t3d',
};
